### ISSUE TITLE
gtfparse dependency causes issues with latest numpy, pandas and pyarrow

### ISSUE THREAD

**Issue by zktuong** [icbi-lab/infercnvpy#143]
### Report

HI @grst,

just wanted to flag to you that with a fresh installation of latest pandas/numpy in the environment, importing `infercnvpy` causes this to come back with `AttributeError: _ARRAY_API not found` similar to problems faced here 
https://github.com/spyder-ide/spyder/issues/22187

To reproduce:
```bash
mamba create -n testi "python=3.11"
mamba activate testi
pip install infercnvpy
python
```

```python
import infercnvpy
```

```pytb
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/__init__.py", line 5, in <module>
    from . import datasets, io, pl, pp, tl
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/datasets/__init__.py", line 5, in <module>
    import scanpy as sc
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/__init__.py", line 20, in <module>
    from ._utils import check_versions
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/_utils/__init__.py", line 27, in <module>
    from anndata import __version__ as anndata_version
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/__init__.py", line 24, in <module>
    from ._core.anndata import AnnData
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/_core/anndata.py", line 18, in <module>
    import pandas as pd
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/__init__.py", line 5, in <module>
    from . import datasets, io, pl, pp, tl
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/datasets/__init__.py", line 5, in <module>
    import scanpy as sc
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/__init__.py", line 20, in <module>
    from ._utils import check_versions
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/_utils/__init__.py", line 27, in <module>
    from anndata import __version__ as anndata_version
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/__init__.py", line 24, in <module>
    from ._core.anndata import AnnData
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/_core/anndata.py", line 18, in <module>
    import pandas as pd
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
```

I found that it's becausse `gtfparse` has a super strict `pyarrow` requirement 
Related to: https://github.com/openvax/gtfparse/issues/47

Forcing installation with `pyarrow>=17.0.0` gets around this but i just have to deal with the pip dependency resolver error.

**Comment by grst** [comment]
thanks for reporting... gtfparse again, I should try to get rid of that package somehow.

**Comment by grst** [comment]
I believe the best solution is to introduce alternative ways of retrieving the genomic positions, see https://github.com/icbi-lab/infercnvpy/issues/144

**Comment by zktuong** [comment]
i think it's resolved by #150

**Comment by HXD3D0323** [comment]
Hi @grst g，

I met a problem. When I use the `cnv.io.genomic_position_from_gtf` in latest infercnvpy version, the same error occur. 

Thank you!

**my install command:**
`conda create -c https://mirrors.pku.edu.cn/anaconda/cloud/conda-forge/ python=3.10 -n infercnvpy
conda activate infercnvpy
pip install infercnvpy
pip install gtfparse==2.1 # 2.5.0 also makes error`

**error info:**
INFO:root:Extracted GTF attributes: ['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'transcript_id', 'transcript_version', 'transcript_name', 'transcript_source', 'transcript_biotype', 'tag', 'transcript_support_level', 'exon_number', 'exon_id', 'exon_version', 'protein_id', 'protein_version', 'ccds_id']

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

```pytb
Traceback (most recent call last):  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 614, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_shell
    await result
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 366, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 827, in execute_request
    reply_content = await reply_content
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 458, in do_execute
    res = shell.run_cell(
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/home/data/t140629/tmpdir/ipykernel_500392/493949050.py", line 9, in <module>
    cnv.io.genomic_position_from_gtf(gtf_file,
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/infercnvpy/io/_genepos.py", line 131, in genomic_position_from_gtf
    gtf = gtfparse.read_gtf(
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/gtfparse/read_gtf.py", line 257, in read_gtf
    features=features)
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/polars/dataframe/frame.py", line 2093, in to_pandas
    return self._to_pandas_without_object_columns(
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/polars/dataframe/frame.py", line 2144, in _to_pandas_without_object_columns
    record_batches = df._df.to_pandas()
  File "/home/data/t140629/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[24], line 9
      1 # ! conda activate infercnvpy
      2 # ! pip install gtfparse==2.1
      3 # ! pip install --upgrade numpy # 解决报错ImportError: numpy.core.multiarray failed to import
      4 # ! pip install "numpy<2.0" # Successfully installed numpy-1.26.4
      5 # ! pip install --force-reinstall pandas pyarrow scipy scanpy scikit-learn
      6 # ! pip install "pyarrow>=14.0.2,<14.1.0" --force-reinstall
      8 gtf_file='/home/data/t140629/geyz/database/genome_reference/Homo_sapiens.GRCh38.114.chr.gtf'
----> 9 cnv.io.genomic_position_from_gtf(gtf_file, 
     10                                  adata=adata, 
     11                                  gtf_gene_id='gene_name', # Use this GTF column to match it to anndata
     12                                  adata_gene_id=None, # Default: use adata.var_names.
     13                                  inplace=True # If True, add the annotations directly to adata, otherwise return a dataframe
     14                                  )
     15 adata

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/infercnvpy/io/_genepos.py:131, in genomic_position_from_gtf(gtf_file, adata, gtf_gene_id, adata_gene_id, inplace)
    127 except ImportError:
    128     raise ImportError(
    129         "genomic_position_from_gtf requires gtfparse as optional dependency. Please install it using `pip install gtfparse`."
    130     ) from None
--> 131 gtf = gtfparse.read_gtf(
    132     gtf_file, usecols=["seqname", "feature", "start", "end", "gene_id", "gene_name"]
    133 ).to_pandas()
    134 gtf = (
    135     gtf.loc[
    136         gtf["feature"] == "gene",
   (...)
    140     .rename(columns={"seqname": "chromosome"})
    141 )
    142 # remove ensembl versions

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/gtfparse/read_gtf.py:257, in read_gtf(filepath_or_buffer, expand_attribute_column, infer_biotype_column, column_converters, column_cast_types, usecols, features, result_type)
    252     result_df = parse_gtf(result_df, features=features)
    254 # converting back to pandas here because Polars bugs manifest
    255 # as `pyo3_runtime.PanicException: assertion `left == right` failed: impl error`
    256 # and are generally insane to chase down
--> 257 result_df = result_df.to_pandas()
    258 if column_converters or column_cast_types:
    259     def wrap_to_always_accept_none(f):

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/polars/dataframe/frame.py:2093, in DataFrame.to_pandas(self, use_pyarrow_extension_array, **kwargs)
   2088 if Object in self.dtypes:
   2089     return self._to_pandas_with_object_columns(
   2090         use_pyarrow_extension_array=use_pyarrow_extension_array, **kwargs
   2091     )
-> 2093 return self._to_pandas_without_object_columns(
   2094     self, use_pyarrow_extension_array=use_pyarrow_extension_array, **kwargs
   2095 )

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/polars/dataframe/frame.py:2144, in DataFrame._to_pandas_without_object_columns(self, df, use_pyarrow_extension_array, **kwargs)
   2141 if not df.width:  # Empty dataframe, cannot infer schema from batches
   2142     return pd.DataFrame()
-> 2144 record_batches = df._df.to_pandas()
   2145 tbl = pa.Table.from_batches(record_batches)
   2146 if use_pyarrow_extension_array:

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/pyarrow/__init__.py:65
     63 _gc_enabled = _gc.isenabled()
     64 _gc.disable()
---> 65 import pyarrow.lib as _lib
     66 if _gc_enabled:
     67     _gc.enable()

File ~/0.tools/miniconda3/envs/infercnvpy/lib/python3.10/site-packages/pyarrow/lib.pyx:36, in init pyarrow.lib()

ImportError: numpy.core.multiarray failed to import
```

**session info:**
```
Package            Version
------------------ -----------
anndata            0.11.4
array-api-compat   1.12.0
asttokens          3.0.1
attrs              25.4.0
cattrs             25.3.0
certifi            2025.11.12
charset-normalizer 3.4.4
comm               0.2.3
contourpy          1.3.2
cycler             0.12.1
debugpy            1.8.17
decorator          5.2.1
exceptiongroup     1.3.0
executing          2.2.1
fonttools          4.60.1
future             1.0.0
gtfparse           2.1.0
h5py               3.15.1
idna               3.11
igraph             1.0.0
importlib_metadata 8.7.0
infercnvpy         0.6.1
iniconfig          2.3.0
ipykernel          7.1.0
ipython            8.37.0
jedi               0.19.2
joblib             1.5.2
jupyter_client     8.6.3
jupyter_core       5.9.1
kiwisolver         1.4.9
legacy-api-wrap    1.5
leidenalg          0.11.0
llvmlite           0.45.1
matplotlib         3.10.7
matplotlib-inline  0.2.1
natsort            8.4.0
nest_asyncio       1.6.0
networkx           3.4.2
numba              0.62.1
numpy              2.2.6
packaging          25.0
pandas             2.3.3
parso              0.8.5
patsy              1.0.2
pexpect            4.9.0
pickleshare        0.7.5
pillow             12.0.0
pip                25.3
platformdirs       4.5.0
pluggy             1.6.0
polars             0.20.31
prompt_toolkit     3.0.52
psutil             7.1.3
ptyprocess         0.7.0
pure_eval          0.2.3
py-cpuinfo         9.0.0
pyarrow            14.0.2
pybiomart          0.2.0
Pygments           2.19.2
pynndescent        0.5.13
pyparsing          3.2.5
pyreadr            0.5.3
pytest             9.0.1
pytest-benchmark   5.2.3
python-dateutil    2.9.0.post0
pytoml             0.1.21
pytz               2025.2
pyzmq              27.1.0
requests           2.32.5
requests-cache     1.2.1
scanpy             1.11.5
scikit-learn       1.7.2
scipy              1.15.3
seaborn            0.13.2
session_info       1.0.1
session-info2      0.2.3
setuptools         80.9.0
six                1.17.0
stack_data         0.6.3
statsmodels        0.14.5
stdlib-list        0.12.0
texttable          1.7.0
threadpoolctl      3.6.0
tomli              2.3.0
tornado            6.5.2
tqdm               4.67.1
traitlets          5.14.3
typing_extensions  4.15.0
tzdata             2025.2
umap-learn         0.5.9.post2
url-normalize      2.2.1
urllib3            2.5.0
wcwidth            0.2.14
wheel              0.45.1
zipp               3.23.0
```

**Comment by grst** [comment]
You have a very old version of `pyarrow` installed. I don't know how you end up with that version in a fresh environment, but can you try updating it? (latest is `pyarrow==22.0.0`)
