### ISSUE TITLE
after  i pip install infercnvpy , when i run "import infercnvpy" , my ipykernel always dies.  

### ISSUE THREAD

**Issue by Gossipforever** [icbi-lab/infercnvpy#145]
### Report

like this
![微信图片_20241101151301](https://github.com/user-attachments/assets/7b5c33ca-a790-42d5-8bbf-5618080968df)

**Comment by Gossipforever** [comment]
![image](https://github.com/user-attachments/assets/5c357915-ca76-4816-a77c-85e447e49ddc)

> ```
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last):  File "<stdin>", line 1, in <module>
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/__init__.py", line 5, in <module>
>     from . import datasets, io, pl, pp, tl
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/datasets/__init__.py", line 5, in <module>
>     import scanpy as sc
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/__init__.py", line 20, in <module>
>     from ._utils import check_versions
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/_utils/__init__.py", line 27, in <module>
>     from anndata import __version__ as anndata_version
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/__init__.py", line 24, in <module>
>     from ._core.anndata import AnnData
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/_core/anndata.py", line 18, in <module>
>     import pandas as pd
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
>     from pandas.compat import (
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
>     from pandas.compat.pyarrow import (
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
>     import pyarrow as pa
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
>     import pyarrow.lib as _lib
> AttributeError: _ARRAY_API not found
> 
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last):  File "<stdin>", line 1, in <module>
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/__init__.py", line 5, in <module>
>     from . import datasets, io, pl, pp, tl
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/infercnvpy/datasets/__init__.py", line 5, in <module>
>     import scanpy as sc
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/__init__.py", line 20, in <module>
>     from ._utils import check_versions
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/scanpy/_utils/__init__.py", line 27, in <module>
>     from anndata import __version__ as anndata_version
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/__init__.py", line 24, in <module>
>     from ._core.anndata import AnnData
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/anndata/_core/anndata.py", line 18, in <module>
>     import pandas as pd
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
>     from pandas.core.api import (
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
>     from pandas.core.dtypes.dtypes import (
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
>     from pandas._libs import (
>   File "/opt/homebrew/Caskroom/mambaforge/base/envs/testi/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
>     import pyarrow.lib as _lib
> AttributeError: _ARRAY_API not found``
> ```

then the kernel died and restart， i try to change  numpy‘s version，and then it has no error but died directly。

**Comment by grst** [comment]
To me this looks a bit like your conda environment is corrupted, possibly by repeatedly installing new packages into it via `pip`. 

I strongly recommend you start creating separate virtual environments for each project. By using the `nb_conda_kernels` package, these venvs will appear as different kernels in jupyter lab.

**Comment by Bioin-Mixologist** [comment]
Changing the installation content might solve the problem.
I encountered similar issues when I installed scanpy, bbknn, and then infercnvpy.
By changing to install **only infercnv**, the error no longer occurs (only warnings remain).
Here is my installation code:
`conda create --name scCNV python=3.10
conda activate scCNV
pip install infercnvpy
conda install ipykernel
pip install ipympl
ipython kernel install --user --name=scCNV-kernel
conda deactivate`

![image](https://github.com/user-attachments/assets/3e76cd24-a41f-4ec3-ace6-df4120401800)

**Comment by grst** [comment]
Looking at your error again, this seems to be the same issue as reported here: https://github.com/icbi-lab/infercnvpy/issues/143

It's a problem with `gtfparse`, an upstream library of infercnvpy. Workaround are described in this issue: https://github.com/openvax/gtfparse/issues/47

I am also working on an alternative way of obtaining genomic positions that works independent of gtfs: #150
